class RegistrationsController < ApplicationController
  def new
  end

  def create
    user = User.new(username: params[:username])
    options = WebAuthn::Credential.options_for_create(
      user: {
        id: user.webauthn_id, # id is required for user
        name: user.username, # name is required for user
      }
    )

    if user.valid?
      session[:current_registration] = {  # ActionDispatch::Request::Session
        challenge: options.challenge, # generated by WebAuthn::Credential.options_for_create(.)
        user_attributes: user.attributes # params, but in JSON format. perrhaps because we will handle JSON later, instead of HTML?
      }
      # TODO: render options as JSON

    end
  end
end
